#!/bin/sh
if [ -f /usr/share/java-utils/java-functions ] ; then
  . /usr/share/java-utils/java-functions
  set_jvm
  set_javacmd
fi

export GRADLE_HOME="${GRADLE_HOME:-/usr/share/gradle}"
export JAVA_HOME; $GRADLE_HOME/bin/gradle "$@"
